services:
  mysql:
    image: mysql:8.0  
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=070809az
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./infrastructure/init.sql:/docker-entrypoint-initdb.d/init.sql