services:

  mongo:
    image: mongo:8.0
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 070809az
      MONGO_INITDB_DATABASE: review_db
    ports:
      - "27018:27017"
    volumes: 
      - mongodb_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
    networks:
     - e-library-network

  book-service:
    build: /bookService
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    container_name: book-service
    ports: 
      - "8080:8080"
    volumes:
      - ./data:/app/data
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - e-library-network

  review-service:
    container_name: review-service
    build: /reviewService
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "8081:8081"
    depends_on:
      mongo: 
        condition: service_healthy
    networks:
      - e-library-network

  api-gateway:
    container_name: api-gateway
    build: /apiGateway
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "9000:9000"
    depends_on:
      book-service: 
        condition: service_started
      review-service: 
        condition: service_started
    networks:
      - e-library-network

  schema-registry:
    image: confluentinc/cp-schema-registry:7.5.0
    hostname: schema-registry
    container_name: schema-registry
    depends_on:
      - broker
    ports:
      - "8082:8082"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'broker:29092'
      SCHEMA_REGISTRY_LISTENERS: http://schema-registry:8082
    networks:
      - e-library-network

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./infrastructure/prometheus/prometheus-prod.yml:/etc/prometheus/prometheus.yml
    networks:
      - e-library-network

volumes:
  mongodb_data: