spring:
  data:
    mongodb:
      uri: mongodb://localhost:27018/
      database: review_db

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/e-library
          jwk-set-uri: http://localhost:8181/realms/e-library/protocol/openid-connect/certs
          token-uri: http://localhost:8181/realms/e-library/protocol/openid-connect/token

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      properties:
        schema:
          registry:
            url: http://localhost:8082
    producer:
      properties:
        schema:
          registry:
            url: http://localhost:8082

book-service:
  url: http://localhost:8080
gateway:
  url: http://localhost:9000

data:
  seeding:
    folder: "../data/seeding/"