spring:
  data:
    mongodb:
      uri: mongodb://root:070809az@mongo:27017/?authSource=admin
      database: review_db

  kafka:
    bootstrap-servers: broker:29092
    consumer:
      group-id: review-service-group
      properties:
        schema:
          registry:
            url: http://schema-registry:8082
    producer:
      properties:
        schema:
          registry:
            url: http://schema-registry:8082

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/e-library
        token-uri: http://keycloak:8080/realms/e-library/protocol/openid-connect/token

kafka:
  topics:
    book-deleted: book-deleted
    book-rating-updated: book-rating-updated
    review-scoring-request: review-scoring-requests
    review-scoring-result: review-scoring-results
    review-matrix-update: review-matrix-updates

book-service:
  url: http://book-service:8080
gateway:
  url: http://api-gateway:9000

data:
  seeding:
    folder: "/app/data/seeding/"