spring.profiles.active=@spring.profiles.active@
spring.application.name=reviewService
server.port=8081

logging.level.org.library.reviewService.client=debug
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG
logging.level.org.springframework.security=DEBUG

springdoc.api-docs.path=/api-docs
openapi.api-docs.token-uri=http://localhost:8181/realms/e-library/protocol/openid-connect/token
openapi.api-docs.auth-uri=http://localhost:8181/realms/e-library/protocol/openid-connect/auth

spring.kafka.consumer.group-id=review-service
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.properties.spring.deserializer.key.delegate.class=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=io.confluent.kafka.serializers.KafkaAvroDeserializer
spring.kafka.consumer.properties.specific.avro.reader=true
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=io.confluent.kafka.serializers.KafkaAvroSerializer
spring.kafka.template.default-topic=book-rating-updated

management.endpoints.web.exposure.include=health, metrics, prometheus
management.endpoint.health.show-details=always

data.seeding.reviews=reviews.json