spring:
  config:
    activate:
      on-profile: dev
services:
  url:
    book: http://localhost:8080
    review: http://localhost:8081
server:
  port: 9000

---

spring:
  config:
    activate:
      on-profile: prod
services:
  url:
    book: http://book-service:8080
    review: http://review-service:8080
server:
  port: 8080