/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package event;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class BookRatingUpdatedEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -1766313582747795206L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"BookRatingUpdatedEvent\",\"namespace\":\"event\",\"fields\":[{\"name\":\"bookId\",\"type\":\"int\"},{\"name\":\"averageRating\",\"type\":\"double\"},{\"name\":\"totalReviews\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<BookRatingUpdatedEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<BookRatingUpdatedEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<BookRatingUpdatedEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<BookRatingUpdatedEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<BookRatingUpdatedEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this BookRatingUpdatedEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a BookRatingUpdatedEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a BookRatingUpdatedEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static BookRatingUpdatedEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private int bookId;
  private double averageRating;
  private int totalReviews;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public BookRatingUpdatedEvent() {}

  /**
   * All-args constructor.
   * @param bookId The new value for bookId
   * @param averageRating The new value for averageRating
   * @param totalReviews The new value for totalReviews
   */
  public BookRatingUpdatedEvent(java.lang.Integer bookId, java.lang.Double averageRating, java.lang.Integer totalReviews) {
    this.bookId = bookId;
    this.averageRating = averageRating;
    this.totalReviews = totalReviews;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return bookId;
    case 1: return averageRating;
    case 2: return totalReviews;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: bookId = (java.lang.Integer)value$; break;
    case 1: averageRating = (java.lang.Double)value$; break;
    case 2: totalReviews = (java.lang.Integer)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'bookId' field.
   * @return The value of the 'bookId' field.
   */
  public int getBookId() {
    return bookId;
  }


  /**
   * Sets the value of the 'bookId' field.
   * @param value the value to set.
   */
  public void setBookId(int value) {
    this.bookId = value;
  }

  /**
   * Gets the value of the 'averageRating' field.
   * @return The value of the 'averageRating' field.
   */
  public double getAverageRating() {
    return averageRating;
  }


  /**
   * Sets the value of the 'averageRating' field.
   * @param value the value to set.
   */
  public void setAverageRating(double value) {
    this.averageRating = value;
  }

  /**
   * Gets the value of the 'totalReviews' field.
   * @return The value of the 'totalReviews' field.
   */
  public int getTotalReviews() {
    return totalReviews;
  }


  /**
   * Sets the value of the 'totalReviews' field.
   * @param value the value to set.
   */
  public void setTotalReviews(int value) {
    this.totalReviews = value;
  }

  /**
   * Creates a new BookRatingUpdatedEvent RecordBuilder.
   * @return A new BookRatingUpdatedEvent RecordBuilder
   */
  public static event.BookRatingUpdatedEvent.Builder newBuilder() {
    return new event.BookRatingUpdatedEvent.Builder();
  }

  /**
   * Creates a new BookRatingUpdatedEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new BookRatingUpdatedEvent RecordBuilder
   */
  public static event.BookRatingUpdatedEvent.Builder newBuilder(event.BookRatingUpdatedEvent.Builder other) {
    if (other == null) {
      return new event.BookRatingUpdatedEvent.Builder();
    } else {
      return new event.BookRatingUpdatedEvent.Builder(other);
    }
  }

  /**
   * Creates a new BookRatingUpdatedEvent RecordBuilder by copying an existing BookRatingUpdatedEvent instance.
   * @param other The existing instance to copy.
   * @return A new BookRatingUpdatedEvent RecordBuilder
   */
  public static event.BookRatingUpdatedEvent.Builder newBuilder(event.BookRatingUpdatedEvent other) {
    if (other == null) {
      return new event.BookRatingUpdatedEvent.Builder();
    } else {
      return new event.BookRatingUpdatedEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for BookRatingUpdatedEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<BookRatingUpdatedEvent>
    implements org.apache.avro.data.RecordBuilder<BookRatingUpdatedEvent> {

    private int bookId;
    private double averageRating;
    private int totalReviews;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(event.BookRatingUpdatedEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.bookId)) {
        this.bookId = data().deepCopy(fields()[0].schema(), other.bookId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.averageRating)) {
        this.averageRating = data().deepCopy(fields()[1].schema(), other.averageRating);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.totalReviews)) {
        this.totalReviews = data().deepCopy(fields()[2].schema(), other.totalReviews);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing BookRatingUpdatedEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(event.BookRatingUpdatedEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.bookId)) {
        this.bookId = data().deepCopy(fields()[0].schema(), other.bookId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.averageRating)) {
        this.averageRating = data().deepCopy(fields()[1].schema(), other.averageRating);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.totalReviews)) {
        this.totalReviews = data().deepCopy(fields()[2].schema(), other.totalReviews);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'bookId' field.
      * @return The value.
      */
    public int getBookId() {
      return bookId;
    }


    /**
      * Sets the value of the 'bookId' field.
      * @param value The value of 'bookId'.
      * @return This builder.
      */
    public event.BookRatingUpdatedEvent.Builder setBookId(int value) {
      validate(fields()[0], value);
      this.bookId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'bookId' field has been set.
      * @return True if the 'bookId' field has been set, false otherwise.
      */
    public boolean hasBookId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'bookId' field.
      * @return This builder.
      */
    public event.BookRatingUpdatedEvent.Builder clearBookId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'averageRating' field.
      * @return The value.
      */
    public double getAverageRating() {
      return averageRating;
    }


    /**
      * Sets the value of the 'averageRating' field.
      * @param value The value of 'averageRating'.
      * @return This builder.
      */
    public event.BookRatingUpdatedEvent.Builder setAverageRating(double value) {
      validate(fields()[1], value);
      this.averageRating = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'averageRating' field has been set.
      * @return True if the 'averageRating' field has been set, false otherwise.
      */
    public boolean hasAverageRating() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'averageRating' field.
      * @return This builder.
      */
    public event.BookRatingUpdatedEvent.Builder clearAverageRating() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'totalReviews' field.
      * @return The value.
      */
    public int getTotalReviews() {
      return totalReviews;
    }


    /**
      * Sets the value of the 'totalReviews' field.
      * @param value The value of 'totalReviews'.
      * @return This builder.
      */
    public event.BookRatingUpdatedEvent.Builder setTotalReviews(int value) {
      validate(fields()[2], value);
      this.totalReviews = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'totalReviews' field has been set.
      * @return True if the 'totalReviews' field has been set, false otherwise.
      */
    public boolean hasTotalReviews() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'totalReviews' field.
      * @return This builder.
      */
    public event.BookRatingUpdatedEvent.Builder clearTotalReviews() {
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public BookRatingUpdatedEvent build() {
      try {
        BookRatingUpdatedEvent record = new BookRatingUpdatedEvent();
        record.bookId = fieldSetFlags()[0] ? this.bookId : (java.lang.Integer) defaultValue(fields()[0]);
        record.averageRating = fieldSetFlags()[1] ? this.averageRating : (java.lang.Double) defaultValue(fields()[1]);
        record.totalReviews = fieldSetFlags()[2] ? this.totalReviews : (java.lang.Integer) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<BookRatingUpdatedEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<BookRatingUpdatedEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<BookRatingUpdatedEvent>
    READER$ = (org.apache.avro.io.DatumReader<BookRatingUpdatedEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeInt(this.bookId);

    out.writeDouble(this.averageRating);

    out.writeInt(this.totalReviews);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.bookId = in.readInt();

      this.averageRating = in.readDouble();

      this.totalReviews = in.readInt();

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.bookId = in.readInt();
          break;

        case 1:
          this.averageRating = in.readDouble();
          break;

        case 2:
          this.totalReviews = in.readInt();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










