spring:
  datasource:
    url: jdbc:mysql://mysql/book_service
    username: root
    password: 070809az

  kafka:
    bootstrap-servers: broker:29092
    consumer:
      properties:
        schema:
          registry:
            url: http://schema-registry:8085
    producer:
      properties:
        schema:
          registry:
            url: http://schema-registry:8085

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/e-library
          token-uri: http://keycloak:8080/realms/e-library/protocol/openid-connect/token

kafka:
  topics:
    book-deleted: book-deleted
    book-rating-updated: book-rating-updated
    book-metadata-changed: book-metadata-changes

gateway:
  url: http://api-gateway:9000

review-service:
  url: http://review-service:8081

recommender-service:
  url: http://recommender-service:8082

feign:
  client:
    config:
      recommender-service:
        connectTimeout: 5000
        readTimeout: 10000
        loggerLevel: FULL
      review-service:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: FULL

data:
  book:
    images: /app/data/book_images/
    url-host: http://localhost:8080
  seeding:
    folder: /app/data/seeding/