spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/book_service
    username: root
    password: root


---


spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://mysql/book_service
    username: root
    password: 070809az