spring.application.name=bookService
spring.profiles.active=@spring.profiles.active@
server.port=8080
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=none

springdoc.api-docs.path=/api-docs
openapi.api-docs.token-uri=http://localhost:8181/realms/e-library/protocol/openid-connect/token

spring.kafka.template.default-topic=book-deleted
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=io.confluent.kafka.serializers.KafkaAvroSerializer

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG

management.endpoints.web.exposure.include=health, metrics, prometheus
management.endpoint.health.show-details=always

data.seeding.categories=categories.json
data.seeding.genres=genres.json
data.seeding.publishers=publishers.json
data.seeding.authors=authors.json
data.seeding.books=books.json

data.book.images.path=/api/book/images/

