name: Review Service CI

on:
  pull_request:
    paths:
      - "reviewService/**"
      - ".github/workflows/**"

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4.7.0
        with:
          distribution: "corretto"
          java-version: "17"
          cache: maven

      - name: Compile of Review service
        run: |
          cd reviewService
          mvn clean compile

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4.7.0
        with:
          distribution: "corretto"
          java-version: "17"
          cache: maven

      - name: Build of Review service
        run: |
          cd reviewService
          mvn clean package -DskipTests

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4.7.0
        with:
          distribution: "corretto"
          java-version: "17"
          cache: maven

      - name: Tests execution of Review service
        run: |
          cd reviewService
          mvn test 
        
      
      
  
